In [37]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN

In [38]:
model = Sequential()

model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 3)                 27        
                                                                 
 dense_2 (Dense)             (None, 1)                 4         
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


### Get Wights and biases

In [39]:
#weights for input layer
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[-0.6348619 ,  0.12918597, -0.21155691],
       [ 0.6736873 ,  0.46246713,  0.1147027 ],
       [-0.78860843,  0.8011909 , -0.0320245 ],
       [ 0.10594416,  0.6105736 , -0.5799236 ],
       [ 0.3678668 , -0.78654164,  0.6249948 ]], dtype=float32)

In [40]:
#weights for first hidden layer
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.08305025,  0.06092087,  0.9946816 ],
       [-0.75430506, -0.65612835, -0.02279437],
       [-0.6512501 ,  0.7521863 , -0.1004445 ]], dtype=float32)

In [41]:
#weights for out put layer
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)

In [42]:
#weights for recurrent network
print(model.get_weights()[3].shape)
model.get_weights()[3]

(3, 1)


array([[ 0.302976  ],
       [-1.006859  ],
       [ 0.11021376]], dtype=float32)

In [43]:
#recurrent for output
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

### Kearas code Example

In [44]:
import numpy 

docs = [
    'go india',
    'india india',
    'hip hip hurray',
    'jeetag bhi jeetaga india jeetaga',
    'bharat mata ki jai',
    'kohli kohli',
    'sachin sachin',
    'dhoni dhoni',
    'modiji ki jai',
    'inqilab Zindabad'
]

In [45]:
from keras.preprocessing.text import Tokenizer
tokenizer =Tokenizer(oov_token='<nothing>')

In [46]:
tokenizer.fit_on_texts(docs)

In [47]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'hip': 3,
 'jeetaga': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'jeetag': 12,
 'bhi': 13,
 'bharat': 14,
 'mata': 15,
 'modiji': 16,
 'inqilab': 17,
 'zindabad': 18}

In [48]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetag', 1),
             ('bhi', 1),
             ('jeetaga', 2),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modiji', 1),
             ('inqilab', 1),
             ('zindabad', 1)])

In [49]:
tokenizer.document_count

10

In [50]:
Sequences = tokenizer.texts_to_sequences(docs)
Sequences

[[10, 2],
 [2, 2],
 [3, 3, 11],
 [12, 13, 4, 2, 4],
 [14, 15, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [16, 5, 6],
 [17, 18]]

In [51]:
from keras.utils import pad_sequences

In [52]:
Sequences=pad_sequences(Sequences, padding='post')

In [53]:
Sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 3,  3, 11,  0,  0],
       [12, 13,  4,  2,  4],
       [14, 15,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [16,  5,  6,  0,  0],
       [17, 18,  0,  0,  0]])

### Semtimenet Analysis with Keras

In [54]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN,Embedding,Flatten

In [55]:
(X_train, y_train),(X_test, y_test)=imdb.load_data()

In [56]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [57]:
X_train.shape

(25000,)

In [58]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [59]:
X_train =pad_sequences(X_train,padding='post',maxlen=50)
X_test =pad_sequences(X_test,padding='post',maxlen=50)

In [60]:
X_train.shape

(25000, 50)

In [61]:
X_test.shape

(25000, 50)

In [62]:
model = Sequential()

model.add(SimpleRNN(32, input_shape=(50,1),return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________


In [63]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')
model.fit(X_train,y_train,epoch=5,validation_data=(X_test,y_test))

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "g:\env\Lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_6020\3731945719.py", line 2, in <module>
    model.fit(X_train,y_train,epoch=5,validation_data=(X_test,y_test))
  File "g:\env\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "g:\env\Lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    filtered_tb = _process_traceback_frames(e.__traceback__)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Model.fit() got an unexpected keyword argument 'epoch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "g:\env\Lib\site-packages\IPython\core\interactiveshell.py", line 2057, in showtraceback
    stb = self.InteractiveTB.structu

### Embedding
* In natural language processing, word embedding isa aterm used for the representation of words for text analysis, typically in the form of a real valued vector that encodes the meaning of the word such that the words that are closer in the vector space are expected to be similar in meaning.